/*
 * Preferences for all optimization-algorithms, combines logic for load/save and GUI
 *
 * Christoph Bodenstein
 * TU-Ilmenau, FG SSE
 */

package timenetexperimentgenerator.optimization;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.SpinnerNumberModel;
import timenetexperimentgenerator.support;
import timenetexperimentgenerator.typedef.*;

/**
 *
 * @author Christoph Bodenstein
 */
public class OptimizerPreferences extends javax.swing.JFrame {
private String propertyFile=System.getProperty("user.home")+File.separatorChar+ ".OptimizerProperties.prop";
private Properties auto=new Properties();

private String pref_LogFileAddon="";
private int pref_WrongSimulationsUntilBreak;
private int pref_WrongSimulationsPerDirection;
private typeOfStartValueEnum pref_StartValue;
private typeOfNeighborhoodEnum pref_NeighborhoodType;
private int pref_SizeOfNeighborhood;
private typeOfAnnealing pref_Annealing;
private double pref_TRatioScale;
private double pref_TAnnealScale;
private double pref_MaxTempParameter;//-->Distance for parameters (Stepwidth)
private double pref_MaxTempCost;//-->Probability of acceptance of bad solutions



    /**
     * Creates new form OptimizerHillPreferences
     */
    public OptimizerPreferences() {
        initComponents();
        this.setPref_WrongSimulationsUntilBreak(support.DEFAULT_WRONG_SOLUTIONS_IN_A_ROW);
        this.setPref_WrongSimulationsPerDirection(support.DEFAULT_WRONG_SOLUTION_PER_DIRECTION);
        this.setPref_SizeOfNeighborhood(support.DEFAULT_SIZE_OF_NEIGHBORHOOD);
        this.setPref_Annealing(support.DEFAULT_TYPE_OF_ANNEALING);

        this.jSpinnerSizeOfNeighborhoodInPercent.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        ((DefaultEditor)this.jSpinnerSizeOfNeighborhoodInPercent.getEditor()).getTextField().setEditable(false);

        ((DefaultEditor)this.jSpinnerWrongSolutionsPerDirectionUntilBreak.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor)this.jSpinnerWrongSolutionsUntilBreak.getEditor()).getTextField().setEditable(false);



        this.loadPreferences();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        measurementForm1 = new timenetexperimentgenerator.MeasurementForm();
        jLabelStartvalueForParameters = new javax.swing.JLabel();
        jComboBoxTypeOfStartValue = new javax.swing.JComboBox();
        jTextFieldLogFileAddon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxAddPrefsToLogfilename = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jComboBoxTypeOfNeighborhood = new javax.swing.JComboBox();
        jLabelTypeOfNeighborhood = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerWrongSolutionsPerDirectionUntilBreak = new javax.swing.JSpinner();
        jSpinnerWrongSolutionsUntilBreak = new javax.swing.JSpinner();
        jLabelWrongSolutionsUntilBreak = new javax.swing.JLabel();
        jLabelWrongSolutionsPerDirectionUntilBreak = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAnnealingMethod = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerMaxTemperatureParameters = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerTemperatureStep = new javax.swing.JSpinner();
        jSpinnerMaxTemperatureCost = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerTRatioScale = new timenetexperimentgenerator.helper.doubleSpinner();
        jSpinnerTAnnealScale = new timenetexperimentgenerator.helper.doubleSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerSizeOfNeighborhoodInPercent = new javax.swing.JSpinner();

        jLabelStartvalueForParameters.setText("Startvalue for parameters");

        jComboBoxTypeOfStartValue.setModel(new DefaultComboBoxModel(typeOfStartValueEnum.values()));
        jComboBoxTypeOfStartValue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTypeOfStartValueItemStateChanged(evt);
            }
        });
        jComboBoxTypeOfStartValue.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxTypeOfStartValueVetoableChange(evt);
            }
        });

        jTextFieldLogFileAddon.setToolTipText("Addon-Text for Logfilename");
        jTextFieldLogFileAddon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogFileAddonActionPerformed(evt);
            }
        });
        jTextFieldLogFileAddon.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldLogFileAddonInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextFieldLogFileAddon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLogFileAddonKeyReleased(evt);
            }
        });
        jTextFieldLogFileAddon.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTextFieldLogFileAddonVetoableChange(evt);
            }
        });

        jLabel4.setText("Addon-Text for Logfile");

        jCheckBoxAddPrefsToLogfilename.setSelected(true);
        jCheckBoxAddPrefsToLogfilename.setText("Add Prefs to Logfilename");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxTypeOfNeighborhood.setModel(new DefaultComboBoxModel(typeOfNeighborhoodEnum.values()));
        jComboBoxTypeOfNeighborhood.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTypeOfNeighborhoodItemStateChanged(evt);
            }
        });
        jComboBoxTypeOfNeighborhood.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxTypeOfNeighborhoodVetoableChange(evt);
            }
        });

        jLabelTypeOfNeighborhood.setText("Type of Neighborhood");

        jSpinnerWrongSolutionsPerDirectionUntilBreak.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerWrongSolutionsPerDirectionUntilBreakStateChanged(evt);
            }
        });
        jSpinnerWrongSolutionsPerDirectionUntilBreak.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jSpinnerWrongSolutionsPerDirectionUntilBreakVetoableChange(evt);
            }
        });

        jSpinnerWrongSolutionsUntilBreak.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerWrongSolutionsUntilBreakStateChanged(evt);
            }
        });
        jSpinnerWrongSolutionsUntilBreak.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jSpinnerWrongSolutionsUntilBreakVetoableChange(evt);
            }
        });

        jLabelWrongSolutionsUntilBreak.setText("Wrong Solutions until break");

        jLabelWrongSolutionsPerDirectionUntilBreak.setText("Wrong Solutions per direction/parameter until break");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWrongSolutionsUntilBreak)
                    .addComponent(jLabelWrongSolutionsPerDirectionUntilBreak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerWrongSolutionsPerDirectionUntilBreak)
                    .addComponent(jSpinnerWrongSolutionsUntilBreak, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerWrongSolutionsUntilBreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerWrongSolutionsPerDirectionUntilBreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelWrongSolutionsUntilBreak, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelWrongSolutionsPerDirectionUntilBreak, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HillClimbing", jPanel1);

        jPanel2.setLayout(null);

        jLabel2.setText("Annealing Method");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 114, 16);

        jComboBoxAnnealingMethod.setModel(new DefaultComboBoxModel(typeOfAnnealing.values()));
        jPanel2.add(jComboBoxAnnealingMethod);
        jComboBoxAnnealingMethod.setBounds(260, 20, 170, 27);

        jLabel3.setText("Max. Temp. for Parameters(T-0-par)");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 50, 230, 16);
        jPanel2.add(jSpinnerMaxTemperatureParameters);
        jSpinnerMaxTemperatureParameters.setBounds(260, 50, 90, 28);

        jLabel5.setText("Temperature-step");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 114, 16);
        jPanel2.add(jSpinnerTemperatureStep);
        jSpinnerTemperatureStep.setBounds(260, 120, 90, 28);
        jPanel2.add(jSpinnerMaxTemperatureCost);
        jSpinnerMaxTemperatureCost.setBounds(260, 80, 90, 28);

        jLabel6.setText("Max. Temp. for Cost(T-0-cost)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 80, 200, 16);

        jLabel7.setText("TRatioScale");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(480, 30, 80, 16);

        jLabel8.setText("TAnnealScale");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(480, 60, 100, 16);
        jPanel2.add(jSpinnerTRatioScale);
        jSpinnerTRatioScale.setBounds(580, 30, 101, 28);
        jPanel2.add(jSpinnerTAnnealScale);
        jSpinnerTAnnealScale.setBounds(580, 60, 101, 28);

        jTabbedPane1.addTab("Simmulated Annealing", jPanel2);

        jLabel1.setText("Size of Neighborhood (in % of Designspace)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStartvalueForParameters, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldLogFileAddon, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(jButton1))
                                        .addComponent(jCheckBoxAddPrefsToLogfilename)))
                                .addGap(292, 292, 292))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTypeOfNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerSizeOfNeighborhoodInPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTypeOfNeighborhood, 0, 146, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTypeOfStartValue, 0, 146, Short.MAX_VALUE))
                                .addGap(347, 347, 347)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxTypeOfStartValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTypeOfNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTypeOfNeighborhood)))
                    .addComponent(jLabelStartvalueForParameters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerSizeOfNeighborhoodInPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxAddPrefsToLogfilename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldLogFileAddon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLogFileAddonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogFileAddonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLogFileAddonActionPerformed

    private void jSpinnerWrongSolutionsPerDirectionUntilBreakVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jSpinnerWrongSolutionsPerDirectionUntilBreakVetoableChange
    
    }//GEN-LAST:event_jSpinnerWrongSolutionsPerDirectionUntilBreakVetoableChange

    private void jSpinnerWrongSolutionsUntilBreakVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jSpinnerWrongSolutionsUntilBreakVetoableChange
    
    }//GEN-LAST:event_jSpinnerWrongSolutionsUntilBreakVetoableChange

    private void jComboBoxTypeOfStartValueVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxTypeOfStartValueVetoableChange
    
    }//GEN-LAST:event_jComboBoxTypeOfStartValueVetoableChange

    private void jTextFieldLogFileAddonVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTextFieldLogFileAddonVetoableChange
    
    }//GEN-LAST:event_jTextFieldLogFileAddonVetoableChange

    private void jComboBoxTypeOfStartValueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTypeOfStartValueItemStateChanged
    
    }//GEN-LAST:event_jComboBoxTypeOfStartValueItemStateChanged

    private void jSpinnerWrongSolutionsUntilBreakStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerWrongSolutionsUntilBreakStateChanged
    
    }//GEN-LAST:event_jSpinnerWrongSolutionsUntilBreakStateChanged

    private void jSpinnerWrongSolutionsPerDirectionUntilBreakStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerWrongSolutionsPerDirectionUntilBreakStateChanged
    
    }//GEN-LAST:event_jSpinnerWrongSolutionsPerDirectionUntilBreakStateChanged

    private void jTextFieldLogFileAddonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldLogFileAddonInputMethodTextChanged
    
    }//GEN-LAST:event_jTextFieldLogFileAddonInputMethodTextChanged

    private void jTextFieldLogFileAddonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLogFileAddonKeyReleased
    
    }//GEN-LAST:event_jTextFieldLogFileAddonKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.savePreferences();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTypeOfNeighborhoodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTypeOfNeighborhoodItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeOfNeighborhoodItemStateChanged

    private void jComboBoxTypeOfNeighborhoodVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxTypeOfNeighborhoodVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeOfNeighborhoodVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxAddPrefsToLogfilename;
    private javax.swing.JComboBox jComboBoxAnnealingMethod;
    public javax.swing.JComboBox jComboBoxTypeOfNeighborhood;
    public javax.swing.JComboBox jComboBoxTypeOfStartValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelStartvalueForParameters;
    private javax.swing.JLabel jLabelTypeOfNeighborhood;
    private javax.swing.JLabel jLabelWrongSolutionsPerDirectionUntilBreak;
    private javax.swing.JLabel jLabelWrongSolutionsUntilBreak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerMaxTemperatureCost;
    private javax.swing.JSpinner jSpinnerMaxTemperatureParameters;
    private javax.swing.JSpinner jSpinnerSizeOfNeighborhoodInPercent;
    private timenetexperimentgenerator.helper.doubleSpinner jSpinnerTAnnealScale;
    private timenetexperimentgenerator.helper.doubleSpinner jSpinnerTRatioScale;
    private javax.swing.JSpinner jSpinnerTemperatureStep;
    private javax.swing.JSpinner jSpinnerWrongSolutionsPerDirectionUntilBreak;
    private javax.swing.JSpinner jSpinnerWrongSolutionsUntilBreak;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldLogFileAddon;
    private timenetexperimentgenerator.MeasurementForm measurementForm1;
    // End of variables declaration//GEN-END:variables


    /**
     * Load Preferences from defined file
     */
    public void loadPreferences(){
    try {
                FileInputStream in=new FileInputStream(propertyFile);
		auto.load(in);
                in.close();

    this.setPref_WrongSimulationsUntilBreak(support.loadIntFromProperties("pref_WrongSimulationsUntilBreak", support.DEFAULT_WRONG_SOLUTIONS_IN_A_ROW, auto));
    //support.log(Integer.toString(support.loadIntFromProperties("pref_WrongSimulationsUntilBreak", getPref_WrongSimulationsUntilBreak(), auto)));
    support.log("Loaded pref_WrongSimulationsUntilBreak is "+getPref_WrongSimulationsUntilBreak());

        this.setPref_WrongSimulationsPerDirection(support.loadIntFromProperties("pref_WrongSimulationsPerDirection", support.DEFAULT_WRONG_SOLUTION_PER_DIRECTION, auto));
    support.log("Loaded pref_WrongSimulationsPerDirection is "+getPref_WrongSimulationsPerDirection());

        this.setPref_SizeOfNeighborhood(support.loadIntFromProperties("pref_SizeOfNeighborhood", support.DEFAULT_SIZE_OF_NEIGHBORHOOD, auto));
    support.log("Loaded Size of Neighborhood is "+getPref_SizeOfNeighborhood());

        this.setPref_StartValue(typeOfStartValueEnum.valueOf(auto.getProperty("pref_StartValue", support.DEFAULT_TYPE_OF_STARTVALUE.toString())));
    support.log("Loaded StartValue is "+getPref_StartValue());

        this.setPref_NeighborhoodType(typeOfNeighborhoodEnum.valueOf(auto.getProperty("pref_NeighborhoodType", support.DEFAULT_TYPE_OF_NEIGHBORHOOD.toString())));
    support.log("Loaded Neighborhoodtype is "+getPref_NeighborhoodType());

        this.setPref_Annealing(typeOfAnnealing.valueOf(auto.getProperty("pref_Annealing", support.DEFAULT_TYPE_OF_ANNEALING.toString())));
    support.log("Loaded Annealing method is "+getPref_Annealing());


    //////
        this.setPref_TScaleRatio(support.loadDoubleFromProperties("pref_TScaleRatio", support.DEFAULT_T_RATIO_SCALE, auto));
    support.log("Loaded TRatioScale is "+getPref_TRatioScale());

        this.setPref_TAnnealScale(support.loadDoubleFromProperties("pref_TAnnealScale", support.DEFAULT_T_ANNEAL_SCALE, auto));
    support.log("Loaded TAnnealScale is "+getPref_TAnnealScale());

        this.setPref_MaxTempParameter(support.loadDoubleFromProperties("pref_MaxTempParameter", support.DEFAULT_MAXTEMP_PARAMETER, auto));
    support.log("Loaded MaxTempParameter is "+getPref_MaxTempParameter());

        this.setPref_MaxTempCost(support.loadDoubleFromProperties("pref_MaxTempCost", support.DEFAULT_MAXTEMP_COST, auto));
    support.log("Loaded MaxTempCost is "+getPref_MaxTempCost());

    ////


        this.setPref_LogFileAddon(auto.getProperty("pref_LogFileAddon", ""));
    support.log("Loaded Optimizer_Logfile-Addon is "+this.jTextFieldLogFileAddon.getText());
                
	} catch (IOException e) {
		// Exception bearbeiten
            support.log("Error while loading Optimizer-Properties.");
	}
    
    }
    
    /**
     * Save Preferences to defined file
     */
    public void savePreferences(){
    support.log("Saving Properties of Optimization");
        try{
        auto.setProperty("pref_WrongSimulationsUntilBreak", Integer.toString(getPref_WrongSimulationsUntilBreak()));
        auto.setProperty("pref_WrongSimulationsPerDirection", Integer.toString(getPref_WrongSimulationsPerDirection()));
        auto.setProperty("pref_SizeOfNeighborhood", Integer.toString(getPref_SizeOfNeighborhood()));

        auto.setProperty("pref_StartValue", getPref_StartValue().toString());
        auto.setProperty("pref_NeighborhoodType", getPref_NeighborhoodType().toString());

        auto.setProperty("pref_Annealing", getPref_Annealing().toString());

        auto.setProperty("pref_TScaleRatio", support.getString(this.getPref_TRatioScale()));

        auto.setProperty("pref_TAnnealScale", support.getString(this.getPref_TAnnealScale()));

        auto.setProperty("pref_MaxTempParameter", support.getString(this.getPref_MaxTempParameter()));

        auto.setProperty("pref_MaxTempCost", support.getString(this.getPref_MaxTempCost()));


        auto.setProperty("pref_LogFileAddon", this.jTextFieldLogFileAddon.getText());
        
        File parserprops =  new File(propertyFile);
        auto.store(new FileOutputStream(parserprops), "ExperimentGenerator-Properties");
        }catch(IOException e){
        support.log("Problem Saving the properties.");
        }
    
    }

    /**
     * @return the pref_WrongSimulationsUntilBreak
     */
    public int getPref_WrongSimulationsUntilBreak() {
        pref_WrongSimulationsUntilBreak=(Integer)this.jSpinnerWrongSolutionsUntilBreak.getValue();
        return pref_WrongSimulationsUntilBreak;
    }

    /**
     * @param pref_WrongSimulationsUntilBreak the pref_WrongSimulationsUntilBreak to set
     */
    public void setPref_WrongSimulationsUntilBreak(int pref_WrongSimulationsUntilBreak) {
        this.pref_WrongSimulationsUntilBreak = pref_WrongSimulationsUntilBreak;
        this.jSpinnerWrongSolutionsUntilBreak.setValue(pref_WrongSimulationsUntilBreak);
    }

    /**
     * @return the pref_WrongSimulationsPerDirection
     */
    public int getPref_WrongSimulationsPerDirection() {
        pref_WrongSimulationsPerDirection=(Integer)this.jSpinnerWrongSolutionsPerDirectionUntilBreak.getValue();
        return pref_WrongSimulationsPerDirection;
    }

    /**
     * @param pref_WrongSimulationsPerDirection the pref_WrongSimulationsPerDirection to set
     */
    public void setPref_WrongSimulationsPerDirection(int pref_WrongSimulationsPerDirection) {
        this.pref_WrongSimulationsPerDirection = pref_WrongSimulationsPerDirection;
        this.jSpinnerWrongSolutionsPerDirectionUntilBreak.setValue(pref_WrongSimulationsPerDirection);
    }

    /**
     * @return the pref_LogFileAddon
     */
    public String getPref_LogFileAddon() {
    this.pref_LogFileAddon=this.jTextFieldLogFileAddon.getText();
    String addonString=pref_LogFileAddon;

        if(this.jCheckBoxAddPrefsToLogfilename.isSelected()){
        addonString+="_WSIMPERDIR_"+this.getPref_WrongSimulationsPerDirection()+"_WSIM_"+this.getPref_WrongSimulationsUntilBreak()+"_StartAt_"+this.jComboBoxTypeOfStartValue.getSelectedItem();
        addonString+="TypOfNeighborhodd_"+this.jComboBoxTypeOfNeighborhood.getSelectedItem();
        }
        return addonString;
    }

    /**
     * @param pref_LogFileAddon the pref_LogFileAddon to set
     */
    public void setPref_LogFileAddon(String pref_LogFileAddon) {
        this.jTextFieldLogFileAddon.setText(pref_LogFileAddon);
        this.pref_LogFileAddon = pref_LogFileAddon;
    }

    /**
     * @return the pref_StartValue
     */
    public typeOfStartValueEnum getPref_StartValue() {
        pref_StartValue=(typeOfStartValueEnum)this.jComboBoxTypeOfStartValue.getSelectedItem();
        return pref_StartValue;
    }

    /**
     * @param pref_StartValue the pref_StartValue to set
     */
    public void setPref_StartValue(typeOfStartValueEnum pref_StartValue) {
        this.jComboBoxTypeOfStartValue.setSelectedItem(pref_StartValue);
        this.pref_StartValue = pref_StartValue;
    }

    /**
     * @return the pref_NeighborhoodType
     */
    public typeOfNeighborhoodEnum getPref_NeighborhoodType() {
        pref_NeighborhoodType=(typeOfNeighborhoodEnum)this.jComboBoxTypeOfNeighborhood.getSelectedItem();
        return pref_NeighborhoodType;
    }

    /**
     * @param pref_NeighborhoodType the pref_NeighborhoodType to set
     */
    public void setPref_NeighborhoodType(typeOfNeighborhoodEnum pref_NeighborhoodType) {
        this.jComboBoxTypeOfNeighborhood.setSelectedItem(pref_NeighborhoodType);
        this.pref_NeighborhoodType = pref_NeighborhoodType;
    }

    /**
     * @return the pref_SizeOfNeighborhood
     */
    public int getPref_SizeOfNeighborhood() {
        this.pref_SizeOfNeighborhood=(Integer)this.jSpinnerSizeOfNeighborhoodInPercent.getValue();
        return pref_SizeOfNeighborhood;
    }

    /**
     * @param pref_SizeOfNeighborhood the pref_SizeOfNeighborhood to set
     */
    public void setPref_SizeOfNeighborhood(int pref_SizeOfNeighborhood) {
        this.jSpinnerSizeOfNeighborhoodInPercent.setValue(pref_SizeOfNeighborhood);
        this.pref_SizeOfNeighborhood = pref_SizeOfNeighborhood;
    }

    /**
     * @return the pref_Annealing, the Type of Annealing
     */
    public typeOfAnnealing getPref_Annealing() {
        this.pref_Annealing=(typeOfAnnealing)this.jComboBoxAnnealingMethod.getSelectedItem();
        return pref_Annealing;
    }

    /**
     * @param pref_Annealing the pref_Annealing to set
     */
    public void setPref_Annealing(typeOfAnnealing pref_Annealing) {
        this.jComboBoxAnnealingMethod.setSelectedItem(pref_Annealing);
        this.pref_Annealing = pref_Annealing;
    }

    /**
     * @return the pref_TRatioScale
     */
    public double getPref_TRatioScale() {
        this.pref_TRatioScale=(Double)this.jSpinnerTRatioScale.getDouble();
        return pref_TRatioScale;
    }

    /**
     * @param pref_TRatioScale the pref_TRatioScale to set
     */
    public void setPref_TScaleRatio(double pref_TScaleRatio) {
        this.jSpinnerTRatioScale.setValue(pref_TScaleRatio);
        this.pref_TRatioScale = pref_TScaleRatio;
    }

    /**
     * @return the pref_TAnnealScale
     */
    public double getPref_TAnnealScale() {
        this.pref_TAnnealScale=(Double)this.jSpinnerTAnnealScale.getDouble();
        return pref_TAnnealScale;
    }

    /**
     * @param pref_TAnnealScale the pref_TAnnealScale to set
     */
    public void setPref_TAnnealScale(double pref_TAnnealScale) {
        this.jSpinnerTAnnealScale.setValue(pref_TAnnealScale);
        this.pref_TAnnealScale = pref_TAnnealScale;
    }

    /**
     * @return the pref_MaxTempParameter
     */
    public double getPref_MaxTempParameter() {
        this.pref_MaxTempParameter=(Double)this.jSpinnerMaxTemperatureParameters.getValue();
        return pref_MaxTempParameter;
    }

    /**
     * @param pref_MaxTempParameter the pref_MaxTempParameter to set
     */
    public void setPref_MaxTempParameter(double pref_MaxTempParameter) {
        this.jSpinnerMaxTemperatureParameters.setValue(pref_MaxTempParameter);
        this.pref_MaxTempParameter = pref_MaxTempParameter;
    }

    /**
     * @return the pref_MaxTempCost
     */
    public double getPref_MaxTempCost() {
        this.pref_MaxTempCost=(Double)jSpinnerMaxTemperatureCost.getValue();
        return pref_MaxTempCost;
    }

    /**
     * @param pref_MaxTempCost the pref_MaxTempCost to set
     */
    public void setPref_MaxTempCost(double pref_MaxTempCost) {
        this.jSpinnerMaxTemperatureCost.setValue(pref_MaxTempCost);
        this.pref_MaxTempCost = pref_MaxTempCost;
    }
    
}
